name: Github Pages

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - 'images/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Add CNAME
      run: |
        mkdir build
        echo "habra.js.org" >> ./build/CNAME
    
    - name: Github Pages Custom Deploy
      uses: sterlingwes/gh-pages-deploy-action@v1.1
      with:
        custom-domain: habra.js.org
        access-token: ${{ secrets.token }}
        source-directory: build
        build-command: npm run build
        
    - name: ls
      run: |
        ls -la
        ls ../ -la
        ls build -la
